/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mgdvobvhllukhhjwgegw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZHZvYnZobGx1a2hoandnZWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDU1MDMsImV4cCI6MjA3MDkyMTUwM30.PnBVDvlV5hkpGG3NDd1HMmX07mzWUBiHgmmODZ3wu-M"
